services:
  app:
    build:
      context: ../
      dockerfile: ./docker/app.dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      migration:
        condition: service_completed_successfully

  migration:
    build:
      context: ../
      dockerfile: ./docker/migration.dockerfile
    restart: no
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.3
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
