include:
  - ../docker-compose.db.yaml
services:
  # override the default service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
