# C# .NET setup and build , result save to cache
on:
  push:
#    paths:
#      - '**.cs'
#      - '**.yaml'
#      - '**.csproj'
#      - '**.dockerfile'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: ./docker-compose.yaml
          shared: true
          bake: true
          up: false

  test:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Docker Compose and Up
        uses: yu-ichiro/spin-up-docker-compose-action@v1
        with:
          file: docker/compose.yaml
          shared: true
          pull: true

