# publish to GitHub Container Registry
on:
  workflow_dispatch:
  push:
    branches:
      - "release/*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # get nbgv version
      - name: tools restore
        run: dotnet tool restore
      - name: Get nbgv version
        id: nbgv
        run: echo "version=$(dotnet nbgv get-version -v NuGetPackageVersion)" >> $GITHUB_ENV
      - name: echo envs
        run: |
          echo "version=${{ env.version }}"
      - name: Publish
        run: |
          dotnet publish BlazorTest.Web --os linux --arch x64 \
            -c Release /p:ContainerImageTags='"latest;${{ env.version }}"' \
            /p:PublishProfile=DefaultContainer \
          || exit 0
