on:
  workflow_dispatch:
  push:
    branches:
      - "release/**"
    paths:
      - '**.cs'
      - '**.yaml'
      - '**.csproj'
      - '**.dockerfile'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish
        run: |
          dotnet publish --os linux --arch x64 -c Release /p:PublishProfile=DefaultContainer
