# C# .NET setup and build, test
on:
  workflow_dispatch:
  push:
    paths:
      - '**.cs'
      - '**.yaml'
      - '**.csproj'
      - '**.dockerfile'

env:
  DB_HOST: db
  DB_PORT: 5432
  DB_USER : postgres
  DB_PASSWORD : postgres
  DB_DATABASE : postgres

jobs:
  tests:
    runs-on: ubuntu-latest
    # for test database
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{ env.DB_USER }}
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
    # restore, build, test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Setup database
        run: dotnet ef database update
      - name: Test
        run: dotnet test
