# C# .NET setup and build, test
on:
  push:
    paths:
      - '**.cs'
      - '**.yaml'
      - '**.csproj'
      - '**.dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    # for test database
    services:
      db:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
    # restore, build, test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
